export const columns = [
  { name: "NAME", uid: "name" },
  { name: "ROLE", uid: "role" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];
export const users = [
  {
    id: 1,
    name: "hany sayed",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "/images/avatar/avatar-3.jpg",
    email: "Mr.reichert@example.com",
  },
  {
    id: 2,
    name: "Amr Samir",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "Amr.lang@example.com",
  },
  {
    id: 3,
    name: "sayed M.",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "/images/avatar/avatar-10.jpg",
    email: "fr.fisher@example.com",
  },
  {
    id: 4,
    name: "hany M.",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "/images/avatar/avatar-7.jpg",
    email: "ha@example.com",
  },
  {
    id: 5,
    name: "jorge K.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 6,
    name: "sayed MU.",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "/images/avatar/avatar-3.jpg",
    email: "Mr.reichert@example.com",
  },
  {
    id: 10,
    name: "Kamel M.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 8,
    name: "sayed M.",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "/images/avatar/avatar-4.jpg",
    email: "fr.fisher@example.com",
  },
  {
    id: 7,
    name: "Amr Samir",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "/images/avatar/avatar-5.jpg",
    email: "Amr.lang@example.com",
  },

  {
    id: 9,
    name: "hade M.",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "/images/avatar/avatar-6.jpg",
    email: "ha@example.com",
  },
  {
    id: 11,
    name: "Muhamed M.",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "/images/avatar/avatar-7.jpg",
    email: "Mr.reichert@example.com",
  },
  {
    id: 12,
    name: "Mahmoud Sayed",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-8.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 13,
    name: "said reda",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "/images/avatar/avatar-10.jpg",
    email: "fr.fisher@example.com",
  },
  {
    id: 14,
    name: "Amr Samir",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "/images/avatar/avatar-1.jpg",
    email: "Amr.lang@example.com",
  },
  {
    id: 15,
    name: "ramzy hany",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "/images/avatar/avatar-3.jpg",
    email: "Mr.reichert@example.com",
  },
  {
    id: 16,
    name: "elghandor M.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 17,
    name: "Mahmoud Sayed",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-8.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 18,
    name: "said reda",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "/images/avatar/avatar-10.jpg",
    email: "fr.fisher@example.com",
  },
  {
    id: 19,
    name: "Amr Samir",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "/images/avatar/avatar-1.jpg",
    email: "Amr.lang@example.com",
  },
  {
    id: 20,
    name: "ramzy hany",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "/images/avatar/avatar-3.jpg",
    email: "Mr.reichert@example.com",
  },
  {
    id: 21,
    name: "elghandor M.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 22,
    name: "elghandor M.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 23,
    name: "elghandor M.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 24,
    name: "elghandor M.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 25,
    name: "elghandor M.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
  {
    id: 26,
    name: "elghandor M.",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "/images/avatar/avatar-2.jpg",
    email: "mail.cooper@example.com",
  },
];
